"""
Fetches country data from FIRST.org Countries API  and generates
a Python module with country mappings for use in the Movie App.

Output: src/data/country_map.py (auto-generated)
"""

import json
import os
from pathlib import Path

import requests

from utils import normalize_title

API_URL = "https://api.first.org/data/v1/countries"

# Where to write the generated module
OUTPUT_PATH = Path("src/data/country_map.py")


def fetch_countries() -> dict:
	"""
	Fetch country data from FIRST.org API.
    Returns the 'data' dict where keys are ISO codes like 'DE', 'NG'.
	"""
	print(f"Fetching countries from {API_URL}...")
	response = requests.get(API_URL, timeout=10)
	response.raise_for_status()

	payload = response.json()
	data = payload.get("data", {})
	if not data:
		raise RuntimeError("No 'data' fields in First.org response")

	print(f"Received {len(data)} countries")
	return data

def build_mappings(data: dict ) -> tuple[dict, dict]:
	"""
	Build two mappings:
      - code_to_name: 'DE' -> 'Germany'
      - name_to_code: 'germany' -> 'DE'
	"""

	code_to_name: dict[str, str] = {}
	name_to_code: dict[str, str] = {}

	for iso_code, info in data.items():
		country_name = info.get("country")
		if not country_name:
			continue

		iso_code = iso_code.upper()
		code_to_name[iso_code] = country_name
		normalized_name = country_name.strip().lower()
		name_to_code[normalized_name] = iso_code
	print(f"Built {len(code_to_name)} code_to_name entries.")
	print(f"Built {len(name_to_code)} name_to_code entries.")
	return code_to_name, name_to_code

def write_python_module(code_to_name: dict, name_to_code: dict) -> None:
	"""
	Write the mappings into src/data/country_map.py as Python dicts.
	"""

	OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)

	header = '''"""
		country_map.py
		Auto-generated by scripts/generate_country_mapping.py
		Contains mappings between ISO 3166-1 alpha-2 codes and country names.
		"""
		'''
	# Use json.dumps to get valid Python literals (They're also valid JSON)
	code_to_name_str = json.dumps(code_to_name, indent=2, sort_keys=True)
	name_to_code_str = json.dumps(name_to_code, indent=2, sort_keys=True)

	body = f"""
		COUNTRY_CODE_TO_NAME = {code_to_name_str}
		
		# Normalized country name (lowercase) -> ISO code (e.g. "germany" -> "DE")
		COUNTRY_NAME_TO_CODE = {name_to_code_str}
	"""

	module_content = header + body

	with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
		f.write(module_content)

	print(f"Wrote country mappings to {OUTPUT_PATH}")

def main()




country_data = fetch_countries()
build_mappings(country_data)